import { z } from 'zod';

// Schema for a single task from NRD parsing
const NarrativeMetadataSchema = z
	.object({
		pov: z.string().optional().describe('Point of view character for this scene/chapter'),
		timeline: z.string().optional().describe('Story timeline period or date'),
		tensionLevel: z
			.union([z.number().int().min(1).max(10), z.string()])
			.optional()
			.describe('Tension level from 1-10 (1=calm, 10=climax)'),
		emotionalBeat: z.string().optional().describe('Emotional state or beat (e.g., fear → resolve)'),
		emotionalStakes: z.string().optional().describe('What is emotionally at stake in this scene'),
		wordCountTarget: z
			.union([z.number().int().positive(), z.string()])
			.optional()
			.describe('Target word count for this chapter/scene'),
		currentWordCount: z
			.number()
			.int()
			.nonnegative()
			.optional()
			.describe('Current word count (updated during drafting)'),
		sensoryNotes: z.string().optional().describe('Sensory details and atmosphere notes'),
		researchHook: z.string().optional().describe('Research questions or worldbuilding needs'),
		continuityCheck: z.string().optional().describe('Continuity validation requirements')
	})
	.optional();

const PRDSingleTaskSchema = z.object({
	id: z.number().int().positive(),
	title: z.string().min(1),
	description: z.string().min(1),
	details: z.string().nullable(),
	testStrategy: z.string().nullable(),
	priority: z.enum(['high', 'medium', 'low']).nullable(),
	dependencies: z.array(z.number().int().positive()).nullable(),
	status: z.string().nullable(),
	metadata: NarrativeMetadataSchema
});

// Schema for the AI response - only expects tasks array since metadata is generated by the code
export const ParsePRDResponseSchema = z.object({
	tasks: z.array(PRDSingleTaskSchema)
});
